"""Retrieves image features generated by LIFEx"""

from common import datasets, datasets_root, feature_prefix,\
     features_root_folder, lifex_raw_features_subfolder,\
     lifex_raw_feature_file, lifex_features, pattern_id_column
from functions import retrieve_lifex_features

for dataset in datasets:
    
    #File where the raw LIFEx-computed features are stored
    lifex_raw_src = (f'{datasets_root}/{dataset}/'
                     f'{lifex_raw_features_subfolder}/'
                     f'{lifex_raw_feature_file}')
    
    #Save the extracted features here
    dst_folder = f'{features_root_folder}/{dataset}'    
    
    for group, features in lifex_features.items():
        df_features = retrieve_lifex_features(
            feature_names=features, lifex_out_file=lifex_raw_src,
            feature_prefix=feature_prefix,
            pattern_id_column=pattern_id_column
        )
            
        destination = (f'{dst_folder}/{group}.csv')
        df_features.to_csv(path_or_buf=destination, index=False)